// Word pairs: [civilianWord, undercoverWord]
// Undercover word is similar but distinct from the civilian word.
const WORDS = {
  en: [
    ["Apple","Pear"],["Banana","Plantain"],["Orange","Tangerine"],["Lemon","Lime"],
    ["Watermelon","Cantaloupe"],["Grape","Raisin"],["Strawberry","Raspberry"],["Pineapple","Mango"],
    ["Cherry","Plum"],["Blueberry","Blackberry"],["Peach","Apricot"],["Coconut","Almond"],
    ["Avocado","Cucumber"],["Tomato","Bell Pepper"],["Carrot","Sweet Potato"],["Potato","Yam"],
    ["Onion","Garlic"],["Broccoli","Cauliflower"],["Lettuce","Cabbage"],["Spinach","Kale"],
    ["Corn","Wheat"],["Rice","Pasta"],["Bread","Bagel"],["Pizza","Calzone"],
    ["Burger","Sandwich"],["Hot Dog","Sausage"],["Ramen","Udon"],["Cake","Pie"],
    ["Cookie","Biscuit"],["Donut","Muffin"],["Chocolate","Candy"],["Ice Cream","Sorbet"],
    ["Pancake","Waffle"],["Cheese","Butter"],["Milk","Yogurt"],["Coffee","Tea"],
    ["Water","Soda"],["Juice","Smoothie"],["Beer","Champagne"],["Whiskey","Vodka"],
    ["Sushi","Sashimi"],["Steak","Ribs"],["Chicken","Turkey"],["Egg","Omelet"],
    ["Soup","Stew"],["Salad","Coleslaw"],["Fries","Chips"],["Popcorn","Nachos"],
    ["Honey","Syrup"],["Sugar","Salt"],
    ["Dog","Wolf"],["Cat","Tiger"],["Lion","Leopard"],["Elephant","Rhino"],
    ["Giraffe","Zebra"],["Horse","Donkey"],["Cow","Buffalo"],["Pig","Boar"],
    ["Sheep","Goat"],["Rabbit","Hamster"],["Mouse","Rat"],["Bear","Panda"],
    ["Fox","Coyote"],["Deer","Elk"],["Monkey","Chimpanzee"],["Gorilla","Orangutan"],
    ["Kangaroo","Koala"],["Penguin","Seagull"],["Eagle","Hawk"],["Parrot","Canary"],
    ["Chicken (bird)","Duck"],["Owl","Bat"],["Pigeon","Dove"],["Peacock","Flamingo"],
    ["Snake","Lizard"],["Crocodile","Alligator"],["Frog","Toad"],["Turtle","Tortoise"],
    ["Shark","Dolphin"],["Whale","Orca"],["Octopus","Squid"],["Crab","Lobster"],
    ["Shrimp","Prawn"],["Jellyfish","Starfish"],["Butterfly","Moth"],["Bee","Wasp"],
    ["Ant","Termite"],["Spider","Scorpion"],["Ladybug","Beetle"],["Dragonfly","Mosquito"],
    ["Fish","Eel"],["Salmon","Tuna"],["Goldfish","Carp"],["Swan","Goose"],
    ["Camel","Llama"],["Hippo","Walrus"],["Hedgehog","Porcupine"],["Squirrel","Chipmunk"],
    ["Raccoon","Skunk"],["Otter","Beaver"],
    ["Beach","Pool"],["Mountain","Hill"],["Forest","Jungle"],["Desert","Savanna"],
    ["River","Lake"],["Ocean","Sea"],["Island","Peninsula"],["City","Village"],
    ["Hospital","Clinic"],["School","University"],["Library","Bookstore"],["Restaurant","Cafe"],
    ["Hotel","Motel"],["Airport","Train Station"],["Zoo","Aquarium"],["Park","Garden"],
    ["Museum","Gallery"],["Cinema","Theater"],["Gym","Stadium"],["Church","Temple"],
    ["Bank","ATM"],["Supermarket","Mall"],["Pharmacy","Drugstore"],["Office","Studio"],
    ["Prison","Dungeon"],["Bridge","Tunnel"],["Castle","Palace"],["Farm","Ranch"],
    ["Factory","Warehouse"],["Embassy","Consulate"],
    ["Car","Truck"],["Bus","Van"],["Bicycle","Motorcycle"],["Train","Subway"],
    ["Airplane","Helicopter"],["Boat","Ship"],["Submarine","Yacht"],["Rocket","Satellite"],
    ["Skateboard","Scooter"],["Taxi","Rideshare"],["Ambulance","Fire Truck"],["Police Car","Patrol Bike"],
    ["Tractor","Bulldozer"],["Tank","Jeep"],["Sailboat","Canoe"],["Hot Air Balloon","Glider"],
    ["Jet Ski","Surfboard"],["Rollerblades","Ice Skates"],["Segway","Hoverboard"],["Carriage","Sleigh"],
    ["Soccer","Rugby"],["Basketball","Volleyball"],["Tennis","Badminton"],["Baseball","Cricket"],
    ["Golf","Bowling"],["Boxing","Wrestling"],["Karate","Judo"],["Swimming","Diving"],
    ["Skiing","Snowboarding"],["Surfing","Kitesurfing"],["Running","Jogging"],["Cycling","Mountain Biking"],
    ["Yoga","Pilates"],["Chess","Checkers"],["Poker","Blackjack"],["Archery","Darts"],
    ["Fencing","Kendo"],["Sailing","Rowing"],["Climbing","Hiking"],["Gymnastics","Ballet"],
    ["Doctor","Nurse"],["Teacher","Professor"],["Lawyer","Judge"],["Chef","Baker"],
    ["Police Officer","Detective"],["Firefighter","Paramedic"],["Pilot","Flight Attendant"],["Soldier","Sailor"],
    ["Farmer","Rancher"],["Engineer","Architect"],["Programmer","Designer"],["Artist","Musician"],
    ["Writer","Journalist"],["Actor","Director"],["Athlete","Coach"],["Dentist","Orthodontist"],
    ["Mechanic","Electrician"],["Plumber","Carpenter"],["Scientist","Researcher"],["Accountant","Banker"],
    ["Phone","Tablet"],["Laptop","Desktop"],["TV","Monitor"],["Camera","Camcorder"],
    ["Watch","Wall Clock"],["Glasses","Sunglasses"],["Book","Magazine"],["Pen","Pencil"],
    ["Notebook","Diary"],["Bag","Backpack"],["Wallet","Purse"],["Key","Lock"],
    ["Umbrella","Raincoat"],["Hat","Cap"],["Shoes","Sandals"],["Shirt","Jacket"],
    ["Pants","Shorts"],["Dress","Skirt"],["Sock","Glove"],["Tie","Scarf"],
    ["Ring","Bracelet"],["Necklace","Earring"],["Fan","Air Conditioner"],["Heater","Fireplace"],
    ["Mirror","Window"],["Couch","Chair"],["Bed","Hammock"],["Table","Desk"],
    ["Lamp","Candle"],["Blanket","Pillow"],
    ["Guitar","Ukulele"],["Piano","Keyboard (music)"],["Drums","Tambourine"],["Violin","Cello"],
    ["Flute","Clarinet"],["Saxophone","Trumpet"],["Microphone","Speaker"],["Concert","Festival"],
    ["Movie","TV Show"],["Novel","Comic"],["Song","Rap"],["Karaoke","Opera"],
    ["Cartoon","Anime"],["Video Game","Board Game"],["Podcast","Radio"],
    ["Sun","Moon"],["Star","Planet"],["Cloud","Fog"],["Rain","Snow"],
    ["Thunder","Lightning"],["Rainbow","Aurora"],["Volcano","Geyser"],["Earthquake","Tsunami"],
    ["Tree","Bush"],["Rose","Tulip"],["Grass","Moss"],["Sand","Gravel"],
    ["Rock","Coral"],["Diamond","Crystal"],["Gold","Silver"],
    ["Wizard","Sorcerer"],["Witch","Fairy"],["Knight","Samurai"],["Dragon","Phoenix"],
    ["Unicorn","Pegasus"],["Vampire","Werewolf"],["Zombie","Ghoul"],["Ghost","Poltergeist"],
    ["Mermaid","Siren"],["Elf","Dwarf"],["Giant","Ogre"],["Goblin","Troll"],
    ["Robot","Cyborg"],["Alien","UFO"],["Superhero","Villain"],["Ninja","Assassin"],
    ["Pirate","Viking"],["Cowboy","Outlaw"],["Genie","Spirit"],["Angel","Demon"],
    ["USA","Canada"],["Japan","South Korea"],["France","Italy"],["Germany","Austria"],
    ["Spain","Portugal"],["India","Pakistan"],["Indonesia","Malaysia"],["Thailand","Vietnam"],
    ["Philippines","Singapore"],["Australia","New Zealand"],["Brazil","Argentina"],["Mexico","Cuba"],
    ["Egypt","Morocco"],["Netherlands","Belgium"],["Turkey","Greece"],
    ["Tokyo","Osaka"],["Paris","London"],["New York","Los Angeles"],["Rome","Athens"],
    ["Jakarta","Bandung"],["Bangkok","Kuala Lumpur"],["Dubai","Abu Dhabi"],["Seoul","Busan"],
    ["Sydney","Melbourne"],["Beijing","Shanghai"],["Madrid","Barcelona"],["Berlin","Munich"],
    ["Toronto","Montreal"],["Hong Kong","Macau"],["Istanbul","Ankara"],
    ["Christmas","Hanukkah"],["New Year","Thanksgiving"],["Halloween","Easter"],["Valentine's Day","Anniversary"],
    ["Birthday","Wedding"],["Graduation","Prom"],["Baby Shower","Bridal Shower"],["Funeral","Memorial"],
    ["Picnic","BBQ"],["Parade","Marathon"],["Carnival","Fair"],["Fireworks","Sparklers"],
    ["Ramadan","Eid"],["Diwali","Holi"],["Mardi Gras","Oktoberfest"],
    ["Head","Skull"],["Hair","Beard"],["Eye","Eyebrow"],["Nose","Mouth"],
    ["Ear","Cheek"],["Tooth","Tongue"],["Lip","Chin"],["Neck","Shoulder"],
    ["Arm","Elbow"],["Hand","Wrist"],["Finger","Thumb"],["Chest","Back"],
    ["Stomach","Navel"],["Hip","Waist"],["Leg","Thigh"],["Knee","Ankle"],
    ["Foot","Toe"],["Heart","Lung"],["Brain","Spine"],["Liver","Kidney"],
    ["Spring","Summer"],["Autumn","Winter"],["Morning","Afternoon"],["Evening","Night"],
    ["Dawn","Dusk"],["Storm","Hurricane"],["Tornado","Cyclone"],["Drought","Flood"],
    ["Heatwave","Cold Snap"],["Sunny","Cloudy"],["Windy","Calm"],["Humid","Dry"],
    ["Typhoon","Blizzard"],["Monsoon","Dry Season"],["Mist","Haze"],
    ["Refrigerator","Freezer"],["Oven","Stove"],["Microwave","Air Fryer"],["Dishwasher","Washing Machine"],
    ["Clothes Dryer","Iron"],["Vacuum","Broom"],["Mop","Duster"],["Kettle","Coffee Maker"],
    ["Blender","Mixer"],["Rice Cooker","Pressure Cooker"],["Thermostat","Smoke Detector"],["Doorbell","Alarm Clock"],
    ["Shower","Bathtub"],["Sink","Faucet"],["Toilet","Bidet"],["Towel","Washcloth"],
    ["Soap","Shampoo"],["Toothbrush","Toothpaste"],["Trash Can","Recycle Bin"],["Curtain","Blind"],
    ["Jigsaw Puzzle","Rubik's Cube"],["Lego","Action Figure"],["Doll","Teddy Bear"],["Toy Car","Toy Plane"],
    ["Kite","Yo-yo"],["Marble","Spinning Top"],["Hula Hoop","Jump Rope"],["Frisbee","Boomerang"],
    ["Slinky","Spring Toy"],["Water Gun","Nerf Gun"],["Trampoline","Bouncy Castle"],["Swing","Slide"],
    ["Seesaw","Carousel"],["Play-Doh","Slime"],["Crayon","Marker"],["Balloon","Bubble"],
    ["Coloring Book","Sticker Book"],["Race Track","Train Set"],["Dice","Playing Cards"],["Hide and Seek","Tag"],
    ["Email","Text Message"],["WiFi","Bluetooth"],["USB","Charger"],["Router","Modem"],
    ["Hard Drive","SSD"],["Printer","Scanner"],["Projector","Smartboard"],["Smartwatch","Fitness Tracker"],
    ["VR Headset","AR Glasses"],["Drone","Quadcopter"],["E-book","Audiobook"],["Blog","Vlog"],
    ["Website","App"],["Browser","Search Engine"],["Password","Username"],["Algorithm","Code"],
    ["Database","Spreadsheet"],["Server","Cloud Storage"],["Hashtag","Emoji"],["Meme","GIF"],
    ["CEO","Manager"],["Secretary","Receptionist"],["Janitor","Gardener"],["Barista","Bartender"],
    ["Waiter","Host"],["Tailor","Seamstress"],["Hairdresser","Barber"],["Makeup Artist","Nail Technician"],
    ["Vet","Zookeeper"],["Librarian","Archivist"],["Astronaut","Astronomer"],["Magician","Clown"],
    ["Photographer","Videographer"],["DJ","Producer"],["Influencer","Content Creator"],
    ["Palm Tree","Pine Tree"],["Oak","Maple"],["Bamboo","Cactus"],["Mushroom","Lichen"],
    ["Waterfall","Rapids"],["Cliff","Canyon"],["Cave","Mine"],["Meadow","Field"],
    ["Swamp","Marsh"],["Glacier","Iceberg"],["Oasis","Reservoir"],["Valley","Gorge"],
    ["Reef","Atoll"],["Fjord","Bay"],["Coast","Shore"],
    ["Croissant","Pretzel"],["Bacon","Ham"],["Taco","Burrito"],["Dumpling","Wonton"],
    ["Curry","Chili"],["Lasagna","Moussaka"],["Risotto","Paella"],["Kebab","Gyro"],
    ["Spring Roll","Samosa"],["Oatmeal","Porridge"],["Granola","Cereal"],["Pudding","Custard"],
    ["Cheesecake","Tiramisu"],["Brownie","Fudge"],["Macaron","Macaroon"],["Caramel","Toffee"],
    ["Gummy Bear","Jelly Bean"],["Marshmallow","Meringue"],["Bubble Tea","Milkshake"],["Lemonade","Iced Tea"],
    ["Espresso","Latte"],["Cappuccino","Mocha"],["Ketchup","Mustard"],["Olive Oil","Vegetable Oil"],
    ["Fried Rice","Fried Noodles"],
    ["Happy","Excited"],["Sad","Lonely"],["Angry","Annoyed"],["Scared","Nervous"],
    ["Surprised","Shocked"],["Proud","Confident"],["Jealous","Envious"],["Tired","Sleepy"],
    ["Bored","Indifferent"],["Grateful","Appreciative"],
    ["Whiteboard","Chalkboard"],["Eraser","Correction Fluid"],["Stapler","Paperclip"],["Ruler","Protractor"],
    ["Glue","Tape"],["Scissors","Cutter"],["Calculator","Abacus"],["Folder","Binder"],
    ["Calendar","Planner"],["Pencil Sharpener","Hole Punch"],
    ["Iguana","Gecko"],["Chameleon","Komodo Dragon"],["Cobra","Python"],["Stork","Crane"],
    ["Hummingbird","Sparrow"],["Woodpecker","Robin"],["Seahorse","Sea Urchin"],["Stingray","Manta Ray"],
    ["Piranha","Barracuda"],["Ostrich","Emu"],["Platypus","Echidna"],["Wombat","Tasmanian Devil"],
    ["Meerkat","Prairie Dog"],["Jaguar","Panther"],["Crow","Raven"]
  ],
  id: [
    ["Apel","Pir"],["Pisang","Pisang Raja"],["Jeruk","Jeruk Mandarin"],["Lemon","Jeruk Nipis"],
    ["Semangka","Melon"],["Anggur","Kismis"],["Stroberi","Raspberry"],["Nanas","Mangga"],
    ["Ceri","Plum"],["Blueberry","Blackberry"],["Persik","Aprikot"],["Kelapa","Almond"],
    ["Alpukat","Mentimun"],["Tomat","Paprika"],["Wortel","Ubi Jalar"],["Kentang","Ubi"],
    ["Bawang Merah","Bawang Putih"],["Brokoli","Kembang Kol"],["Selada","Kubis"],["Bayam","Kangkung"],
    ["Jagung","Gandum"],["Nasi","Pasta"],["Roti","Bagel"],["Pizza","Calzone"],
    ["Burger","Sandwich"],["Hot Dog","Sosis"],["Ramen","Udon"],["Kue","Pie"],
    ["Kue Kering","Biskuit"],["Donat","Muffin"],["Cokelat","Permen"],["Es Krim","Sorbet"],
    ["Pancake","Wafel"],["Keju","Mentega"],["Susu","Yogurt"],["Kopi","Teh"],
    ["Air Putih","Soda"],["Jus","Smoothie"],["Bir","Sampanye"],["Wiski","Vodka"],
    ["Sushi","Sashimi"],["Steak","Iga"],["Ayam","Kalkun"],["Telur","Omelet"],
    ["Sup","Soto"],["Salad","Gado-gado"],["Kentang Goreng","Keripik"],["Popcorn","Nachos"],
    ["Madu","Sirup"],["Gula","Garam"],
    ["Anjing","Serigala"],["Kucing","Harimau"],["Singa","Macan Tutul"],["Gajah","Badak"],
    ["Jerapah","Zebra"],["Kuda","Keledai"],["Sapi","Kerbau"],["Babi","Babi Hutan"],
    ["Domba","Kambing"],["Kelinci","Hamster"],["Tikus","Tikus Got"],["Beruang","Panda"],
    ["Rubah","Anjing Liar"],["Rusa","Kijang"],["Monyet","Simpanse"],["Gorila","Orangutan"],
    ["Kanguru","Koala"],["Penguin","Burung Camar"],["Elang","Rajawali"],["Burung Beo","Kenari"],
    ["Ayam Kampung","Bebek"],["Burung Hantu","Kelelawar"],["Merpati","Dara"],["Merak","Flamingo"],
    ["Ular","Kadal"],["Buaya","Aligator"],["Katak","Kodok"],["Kura-kura","Penyu"],
    ["Hiu","Lumba-lumba"],["Paus","Orca"],["Gurita","Cumi-cumi"],["Kepiting","Lobster"],
    ["Udang","Udang Galah"],["Ubur-ubur","Bintang Laut"],["Kupu-kupu","Ngengat"],["Lebah","Tawon"],
    ["Semut","Rayap"],["Laba-laba","Kalajengking"],["Kumbang","Kunang-kunang"],["Capung","Nyamuk"],
    ["Ikan","Belut"],["Salmon","Tuna"],["Ikan Mas","Koi"],["Angsa","Bebek Liar"],
    ["Unta","Lama"],["Kuda Nil","Walrus"],["Landak","Trenggiling"],["Tupai","Bajing"],
    ["Rakun","Sigung"],["Berang-berang","Musang"],
    ["Pantai","Kolam Renang"],["Gunung","Bukit"],["Hutan","Rimba"],["Gurun","Sabana"],
    ["Sungai","Danau"],["Laut","Samudra"],["Pulau","Semenanjung"],["Kota","Desa"],
    ["Rumah Sakit","Klinik"],["Sekolah","Universitas"],["Perpustakaan","Toko Buku"],["Restoran","Kafe"],
    ["Hotel","Losmen"],["Bandara","Stasiun Kereta"],["Kebun Binatang","Akuarium"],["Taman","Kebun"],
    ["Museum","Galeri"],["Bioskop","Teater"],["Gym","Stadion"],["Gereja","Masjid"],
    ["Bank","ATM"],["Supermarket","Mall"],["Apotek","Toko Obat"],["Kantor","Studio"],
    ["Penjara","Sel Tahanan"],["Jembatan","Terowongan"],["Istana","Kastil"],["Peternakan","Ladang"],
    ["Pabrik","Gudang"],["Kedutaan","Konsulat"],
    ["Mobil","Truk"],["Bus","Van"],["Sepeda","Motor"],["Kereta","MRT"],
    ["Pesawat","Helikopter"],["Perahu","Kapal"],["Kapal Selam","Yacht"],["Roket","Satelit"],
    ["Skateboard","Skuter"],["Taksi","Ojek"],["Ambulans","Mobil Damkar"],["Mobil Polisi","Motor Patroli"],
    ["Traktor","Buldoser"],["Tank","Jip"],["Kapal Layar","Kano"],["Balon Udara","Glider"],
    ["Jet Ski","Papan Selancar"],["Sepatu Roda","Sepatu Es"],["Segway","Hoverboard"],["Kereta Kuda","Delman"],
    ["Sepak Bola","Rugby"],["Basket","Voli"],["Tenis","Bulu Tangkis"],["Bisbol","Kriket"],
    ["Golf","Boling"],["Tinju","Gulat"],["Karate","Judo"],["Renang","Selam"],
    ["Ski","Snowboarding"],["Selancar","Kitesurfing"],["Lari","Jogging"],["Bersepeda","Sepeda Gunung"],
    ["Yoga","Pilates"],["Catur","Dam"],["Poker","Blackjack"],["Panahan","Dart"],
    ["Anggar","Kendo"],["Berlayar","Mendayung"],["Panjat Tebing","Mendaki"],["Senam","Balet"],
    ["Dokter","Perawat"],["Guru","Dosen"],["Pengacara","Hakim"],["Koki","Tukang Roti"],
    ["Polisi","Detektif"],["Pemadam Kebakaran","Paramedis"],["Pilot","Pramugari"],["Tentara","Pelaut"],
    ["Petani","Peternak"],["Insinyur","Arsitek"],["Programmer","Desainer"],["Seniman","Musisi"],
    ["Penulis","Wartawan"],["Aktor","Sutradara"],["Atlet","Pelatih"],["Dokter Gigi","Ortodontis"],
    ["Montir","Tukang Listrik"],["Tukang Ledeng","Tukang Kayu"],["Ilmuwan","Peneliti"],["Akuntan","Bankir"],
    ["HP","Tablet"],["Laptop","Komputer"],["TV","Monitor"],["Kamera","Handycam"],
    ["Jam Tangan","Jam Dinding"],["Kacamata","Kacamata Hitam"],["Buku","Majalah"],["Pulpen","Pensil"],
    ["Buku Catatan","Diari"],["Tas","Ransel"],["Dompet","Tas Tangan"],["Kunci","Gembok"],
    ["Payung","Jas Hujan"],["Topi","Peci"],["Sepatu","Sandal"],["Kemeja","Jaket"],
    ["Celana","Celana Pendek"],["Gaun","Rok"],["Kaus Kaki","Sarung Tangan"],["Dasi","Syal"],
    ["Cincin","Gelang"],["Kalung","Anting"],["Kipas","AC"],["Pemanas","Perapian"],
    ["Cermin","Jendela"],["Sofa","Kursi"],["Kasur","Hammock"],["Meja","Meja Belajar"],
    ["Lampu","Lilin"],["Selimut","Bantal"],
    ["Gitar","Ukulele"],["Piano","Keyboard Musik"],["Drum","Rebana"],["Biola","Cello"],
    ["Seruling","Klarinet"],["Saksofon","Terompet"],["Mikrofon","Speaker"],["Konser","Festival"],
    ["Film","Acara TV"],["Novel","Komik"],["Lagu","Rap"],["Karaoke","Opera"],
    ["Kartun","Anime"],["Video Game","Board Game"],["Podcast","Radio"],
    ["Matahari","Bulan"],["Bintang","Planet"],["Awan","Kabut"],["Hujan","Salju"],
    ["Petir","Guntur"],["Pelangi","Aurora"],["Gunung Berapi","Geyser"],["Gempa Bumi","Tsunami"],
    ["Pohon","Semak"],["Mawar","Tulip"],["Rumput","Lumut"],["Pasir","Kerikil"],
    ["Batu","Karang"],["Berlian","Kristal"],["Emas","Perak"],
    ["Penyihir","Dukun"],["Nenek Sihir","Peri"],["Ksatria","Samurai"],["Naga","Phoenix"],
    ["Unicorn","Pegasus"],["Vampir","Manusia Serigala"],["Zombi","Ghoul"],["Hantu","Arwah"],
    ["Putri Duyung","Sirene"],["Elf","Kurcaci"],["Raksasa","Buto"],["Goblin","Troll"],
    ["Robot","Cyborg"],["Alien","UFO"],["Pahlawan Super","Penjahat"],["Ninja","Pembunuh Bayaran"],
    ["Bajak Laut","Viking"],["Koboi","Perampok"],["Jin","Roh"],["Malaikat","Iblis"],
    ["Amerika","Kanada"],["Jepang","Korea Selatan"],["Prancis","Italia"],["Jerman","Austria"],
    ["Spanyol","Portugal"],["India","Pakistan"],["Indonesia","Malaysia"],["Thailand","Vietnam"],
    ["Filipina","Singapura"],["Australia","Selandia Baru"],["Brasil","Argentina"],["Meksiko","Kuba"],
    ["Mesir","Maroko"],["Belanda","Belgia"],["Turki","Yunani"],
    ["Tokyo","Osaka"],["Paris","London"],["New York","Los Angeles"],["Roma","Athena"],
    ["Jakarta","Bandung"],["Bangkok","Kuala Lumpur"],["Dubai","Abu Dhabi"],["Seoul","Busan"],
    ["Sydney","Melbourne"],["Beijing","Shanghai"],["Madrid","Barcelona"],["Berlin","Munich"],
    ["Toronto","Montreal"],["Hong Kong","Makau"],["Istanbul","Ankara"],
    ["Natal","Hanukkah"],["Tahun Baru","Thanksgiving"],["Halloween","Paskah"],["Hari Valentine","Hari Jadi"],
    ["Ulang Tahun","Pernikahan"],["Wisuda","Prom"],["Baby Shower","Bridal Shower"],["Pemakaman","Peringatan"],
    ["Piknik","BBQ"],["Parade","Maraton"],["Karnaval","Pasar Malam"],["Kembang Api","Kembang Pijar"],
    ["Ramadan","Idul Fitri"],["Diwali","Holi"],["Imlek","Cap Go Meh"],
    ["Kepala","Tengkorak"],["Rambut","Jenggot"],["Mata","Alis"],["Hidung","Mulut"],
    ["Telinga","Pipi"],["Gigi","Lidah"],["Bibir","Dagu"],["Leher","Bahu"],
    ["Lengan","Siku"],["Tangan","Pergelangan Tangan"],["Jari","Jempol"],["Dada","Punggung"],
    ["Perut","Pusar"],["Pinggul","Pinggang"],["Kaki","Paha"],["Lutut","Pergelangan Kaki"],
    ["Telapak Kaki","Jari Kaki"],["Jantung","Paru-paru"],["Otak","Tulang Belakang"],["Hati","Ginjal"],
    ["Musim Semi","Musim Panas"],["Musim Gugur","Musim Dingin"],["Pagi","Siang"],["Sore","Malam"],
    ["Subuh","Senja"],["Badai","Angin Ribut"],["Puting Beliung","Tornado"],["Kekeringan","Banjir"],
    ["Gelombang Panas","Cuaca Ekstrem Dingin"],["Cerah","Mendung"],["Berangin","Tenang"],["Lembap","Kering"],
    ["Topan","Badai Salju"],["Musim Hujan","Musim Kemarau"],["Kabut Tipis","Kabut Asap"],
    ["Kulkas","Freezer"],["Oven","Kompor"],["Microwave","Air Fryer"],["Mesin Cuci Piring","Mesin Cuci Baju"],
    ["Pengering","Setrika"],["Vacuum Cleaner","Sapu"],["Pel","Kemoceng"],["Teko","Mesin Kopi"],
    ["Blender","Mixer"],["Rice Cooker","Presto"],["Termostat","Detektor Asap"],["Bel Pintu","Jam Weker"],
    ["Shower","Bak Mandi"],["Wastafel","Keran"],["Toilet","Bidet"],["Handuk","Lap"],
    ["Sabun","Sampo"],["Sikat Gigi","Pasta Gigi"],["Tempat Sampah","Kotak Daur Ulang"],["Gorden","Tirai"],
    ["Puzzle","Rubik"],["Lego","Action Figure"],["Boneka","Teddy Bear"],["Mobil Mainan","Pesawat Mainan"],
    ["Layangan","Yoyo"],["Kelereng","Gasing"],["Hula Hoop","Lompat Tali"],["Frisbee","Bumerang"],
    ["Slinky","Pegas"],["Pistol Air","Pistol Nerf"],["Trampolin","Istana Balon"],["Ayunan","Perosotan"],
    ["Jungkat-jungkit","Komidi Putar"],["Lilin Mainan","Slime"],["Krayon","Spidol"],["Balon","Gelembung Sabun"],
    ["Buku Mewarnai","Buku Stiker"],["Lintasan Balap","Set Kereta"],["Dadu","Kartu Remi"],["Petak Umpet","Kejar-kejaran"],
    ["Email","SMS"],["WiFi","Bluetooth"],["USB","Charger"],["Router","Modem"],
    ["Hard Disk","SSD"],["Printer","Scanner"],["Proyektor","Smartboard"],["Jam Pintar","Pelacak Kebugaran"],
    ["Headset VR","Kacamata AR"],["Drone","Quadcopter"],["E-book","Audiobook"],["Blog","Vlog"],
    ["Website","Aplikasi"],["Browser","Mesin Pencari"],["Password","Username"],["Algoritma","Kode"],
    ["Database","Spreadsheet"],["Server","Cloud Storage"],["Hashtag","Emoji"],["Meme","GIF"],
    ["CEO","Manajer"],["Sekretaris","Resepsionis"],["Petugas Kebersihan","Tukang Kebun"],["Barista","Bartender"],
    ["Pelayan","Kasir"],["Penjahit","Perancang Busana"],["Penata Rambut","Tukang Cukur"],["Penata Rias","Manikur"],
    ["Dokter Hewan","Penjaga Kebun Binatang"],["Pustakawan","Arsiparis"],["Astronot","Astronom"],["Pesulap","Badut"],
    ["Fotografer","Videografer"],["DJ","Produser"],["Influencer","Kreator Konten"],
    ["Pohon Palem","Pohon Pinus"],["Pohon Oak","Pohon Mapel"],["Bambu","Kaktus"],["Jamur","Ragi"],
    ["Air Terjun","Jeram"],["Tebing","Jurang"],["Gua","Tambang"],["Padang Rumput","Sawah"],
    ["Rawa","Paya"],["Gletser","Gunung Es"],["Oasis","Waduk"],["Lembah","Ngarai"],
    ["Terumbu","Atol"],["Fjord","Teluk"],["Pesisir","Garis Pantai"],
    ["Croissant","Pretzel"],["Bacon","Ham"],["Taco","Burrito"],["Pangsit","Siomay"],
    ["Kari","Rendang"],["Lasagna","Moussaka"],["Risotto","Paella"],["Kebab","Gyro"],
    ["Lumpia","Martabak"],["Bubur","Havermut"],["Granola","Sereal"],["Puding","Custard"],
    ["Cheesecake","Tiramisu"],["Brownies","Fudge"],["Macaron","Macaroon"],["Karamel","Tofi"],
    ["Permen Karet","Agar-agar"],["Marshmallow","Meringue"],["Bubble Tea","Milkshake"],["Limun","Es Teh"],
    ["Espresso","Latte"],["Cappuccino","Mocha"],["Saus Tomat","Mustar"],["Minyak Zaitun","Minyak Sayur"],
    ["Nasi Goreng","Mie Goreng"],
    ["Bahagia","Bersemangat"],["Sedih","Kesepian"],["Marah","Kesal"],["Takut","Gugup"],
    ["Terkejut","Tercengang"],["Bangga","Percaya Diri"],["Iri","Cemburu"],["Lelah","Mengantuk"],
    ["Bosan","Acuh"],["Bersyukur","Berterima Kasih"],
    ["Papan Tulis","Whiteboard"],["Penghapus","Tip-Ex"],["Stapler","Klip Kertas"],["Penggaris","Busur Derajat"],
    ["Lem","Selotip"],["Gunting","Cutter"],["Kalkulator","Sempoa"],["Map","Binder"],
    ["Kalender","Agenda"],["Rautan","Pembolong Kertas"],
    ["Iguana","Tokek"],["Bunglon","Komodo"],["Kobra","Piton"],["Bangau","Kuntul"],
    ["Kolibri","Pipit"],["Pelatuk","Kutilang"],["Kuda Laut","Bulu Babi"],["Ikan Pari","Manta"],
    ["Piranha","Barakuda"],["Burung Unta","Kasuari"],["Platypus","Ekidna"],["Wombat","Setan Tasmania"],
    ["Meerkat","Anjing Padang"],["Jaguar","Macan Kumbang"],["Gagak","Murai"]
  ]
};
